//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurriculaBaseCompetencia
    {
        public CurriculaBaseCompetencia()
        {
            this.PlanEstudiosBase = new HashSet<PlanEstudiosBase>();
        }
    
        public int IdCurriculaBaseCompetencia { get; set; }
        public int IdCurriculaBase { get; set; }
        public int IdCompetencia { get; set; }
        public Nullable<int> IdAreaCurricular { get; set; }
    
        public virtual AreaCurricular AreaCurricular { get; set; }
        public virtual Competencia Competencia { get; set; }
        public virtual CurriculaBase CurriculaBase { get; set; }
        public virtual ICollection<PlanEstudiosBase> PlanEstudiosBase { get; set; }
    }
}
