//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.PlanEstudiosBase = new HashSet<PlanEstudiosBase>();
            this.Docente = new HashSet<Docente>();
        }
    
        public int IdCurso { get; set; }
        public string Nombre { get; set; }
        public string Descripción { get; set; }
        public int IdGrado { get; set; }
        public int IdAreaCurricular { get; set; }
    
        public virtual AreaCurricular AreaCurricular { get; set; }
        public virtual Grado Grado { get; set; }
        public virtual ICollection<PlanEstudiosBase> PlanEstudiosBase { get; set; }
        public virtual ICollection<Docente> Docente { get; set; }
    }
}
