//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grado
    {
        public Grado()
        {
            this.Curso = new HashSet<Curso>();
        }
    
        public int IdGrado { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int IdNivel { get; set; }
    
        public virtual ICollection<Curso> Curso { get; set; }
        public virtual Nivel Nivel { get; set; }
    }
}
