//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nivel
    {
        public Nivel()
        {
            this.Curricula = new HashSet<Curricula>();
            this.Grado = new HashSet<Grado>();
        }
    
        public int IdNivel { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Curricula> Curricula { get; set; }
        public virtual ICollection<Grado> Grado { get; set; }
    }
}
