//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanEstudiosBase
    {
        public int IdCurriculaBaseCompetencia { get; set; }
        public int IdCurso { get; set; }
        public decimal Horas { get; set; }
    
        public virtual CurriculaBaseCompetencia CurriculaBaseCompetencia { get; set; }
        public virtual Curso Curso { get; set; }
    }
}
